### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [sudo-panda/PyHEP-2022#2]
Hello @sudo-panda, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by sudo-panda** [comment]
Hi @eduardo-rodrigues I have created a tag for the repo. Do I need to do anything else?

**Comment by eduardo-rodrigues** [comment]
That's all. I take the care of the rest manually in Zenodo. Thanks again.
